services:
  db:
    image: postgres:16-alpine
    container_name: intern_task_2_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: intern_task_2_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d intern_task_2_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: intern_task_2_backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=intern_task_2_db;Username=admin;Password=admin123"
      Jwt__Key: "my-super-secret-jwt-key-minimum-32-chars!!"
      Jwt__Issuer: "intern_task_2"
      Jwt__Audience: "intern_task_2"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5291:5291"

  tests:
    image: node:22-alpine
    container_name: intern_task_2_tests
    working_dir: /tests
    depends_on:
      - backend
      - db
    volumes:
      - ./tests:/tests
    entrypoint: ["sh", "/tests/run-tests.sh"]
    environment:
      API_HOST: backend
      DB_HOST: db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: intern_task_2_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4200:4200"

volumes:
  pg_data:
